name: Test Workflow
on: [workflow_dispatch]
jobs:
  test-job-1:
    name: First Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run a test
        run: |
          echo "Test 1 - 1: " "$?"
          true
          echo "Test 1 - 2:" "$?"
          false
          echo "Test 1 - 3:" "$?"
          true; echo "Test 1 - 4:" "$?"
          false; echo "Test 1 - 5:" "$?"
  test-job-2:
    name: Second Test
    # Test if this job is ran even if the first fails
    #needs: test-job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run a test
        run: |
          cd cmake-test
          # When using scripts, care must be taken with the return status.
          # Scripts usually do not stop execution when a command fails, like in
          # Github workflows.
          # Consider using "set -euo"
          ./build-and-run-test.sh
          echo "Test 2 status: $?"
